<?php

namespace App\View\Components\Dashboard;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class StatistikMahasiswa extends Component
{
    public string $title;

    public string $subtitle;

    public array $summaryCards;

    public array $academicYears;

    public array $semesters;

    public array $faculties;

    public array $chartPayload;

    public function __construct(
        string $title = 'Statistik Mahasiswa',
        string $subtitle = 'Ringkasan mahasiswa per fakultas dengan filter tahun akademik, semester, dan fakultas.'
    ) {
        $this->title = $title;
        $this->subtitle = $subtitle;
        $this->academicYears = ['2024/2025', '2023/2024', '2022/2023'];
        $this->semesters = ['Ganjil', 'Genap', 'Pendek'];
        $this->faculties = ['Semua Fakultas', 'FKIP', 'FEB', 'FT', 'FISIP', 'FH', 'FP', 'FK'];
        $this->summaryCards = $this->buildSummaryCards();
        $this->chartPayload = [
            'filters' => [
                'years' => $this->academicYears,
                'semesters' => $this->semesters,
                'faculties' => $this->faculties,
            ],
            'defaultSelection' => [
                'year' => '2024/2025',
                'semester' => 'Ganjil',
                'faculty' => 'Semua Fakultas',
            ],
            'chartCatalog' => $this->buildChartCatalog(),
        ];
    }

    public function render(): View|Closure|string
    {
        return view('components.dashboard.statistik-mahasiswa', [
            'title' => $this->title,
            'subtitle' => $this->subtitle,
            'summaryCards' => $this->summaryCards,
            'academicYears' => $this->academicYears,
            'semesters' => $this->semesters,
            'faculties' => $this->faculties,
            'chartPayload' => $this->chartPayload,
        ]);
    }

    private function buildSummaryCards(): array
    {
        return [
            [
                'label' => 'Total Mahasiswa',
                'value' => 7901,
                'accentBg' => 'bg-gray-custom-400/40',
                'accentText' => 'text-gray-custom-600',
            ],
            [
                'label' => 'Mahasiswa Aktif',
                'value' => 6345,
                'accentBg' => 'bg-blue-custom-400/15',
                'accentText' => 'text-blue-custom-500',
            ],
            [
                'label' => 'Mahasiswa Baru',
                'value' => 854,
                'accentBg' => 'bg-green-400/15',
                'accentText' => 'text-green-500',
            ],
            [
                'label' => 'Mahasiswa Lulus',
                'value' => 519,
                'accentBg' => 'bg-cyan-custom-400/15',
                'accentText' => 'text-cyan-custom-500',
            ],
        ];
    }

    private function buildChartCatalog(): array
    {
        return [
            '2024/2025' => [
                'Ganjil' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1240,
                        'new' => 185,
                        'graduate' => 102,
                        'inactive' => 34,
                        'male' => 760,
                        'female' => 801,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 980,
                        'new' => 132,
                        'graduate' => 84,
                        'inactive' => 28,
                        'male' => 548,
                        'female' => 676,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1105,
                        'new' => 160,
                        'graduate' => 91,
                        'inactive' => 37,
                        'male' => 878,
                        'female' => 515,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 890,
                        'new' => 118,
                        'graduate' => 76,
                        'inactive' => 29,
                        'male' => 432,
                        'female' => 681,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 760,
                        'new' => 95,
                        'graduate' => 63,
                        'inactive' => 21,
                        'male' => 393,
                        'female' => 546,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 720,
                        'new' => 88,
                        'graduate' => 54,
                        'inactive' => 18,
                        'male' => 302,
                        'female' => 578,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 650,
                        'new' => 76,
                        'graduate' => 49,
                        'inactive' => 16,
                        'male' => 234,
                        'female' => 557,
                    ],
                ],
                'Genap' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1215,
                        'new' => 168,
                        'graduate' => 115,
                        'inactive' => 30,
                        'male' => 748,
                        'female' => 780,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 962,
                        'new' => 120,
                        'graduate' => 90,
                        'inactive' => 25,
                        'male' => 532,
                        'female' => 665,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1088,
                        'new' => 143,
                        'graduate' => 96,
                        'inactive' => 33,
                        'male' => 860,
                        'female' => 500,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 870,
                        'new' => 106,
                        'graduate' => 82,
                        'inactive' => 27,
                        'male' => 420,
                        'female' => 665,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 748,
                        'new' => 89,
                        'graduate' => 69,
                        'inactive' => 19,
                        'male' => 388,
                        'female' => 537,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 701,
                        'new' => 82,
                        'graduate' => 58,
                        'inactive' => 16,
                        'male' => 290,
                        'female' => 567,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 640,
                        'new' => 69,
                        'graduate' => 52,
                        'inactive' => 14,
                        'male' => 228,
                        'female' => 547,
                    ],
                ],
                'Pendek' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1188,
                        'new' => 150,
                        'graduate' => 109,
                        'inactive' => 28,
                        'male' => 730,
                        'female' => 745,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 950,
                        'new' => 114,
                        'graduate' => 86,
                        'inactive' => 24,
                        'male' => 525,
                        'female' => 649,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1070,
                        'new' => 136,
                        'graduate' => 93,
                        'inactive' => 31,
                        'male' => 845,
                        'female' => 485,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 858,
                        'new' => 98,
                        'graduate' => 79,
                        'inactive' => 24,
                        'male' => 410,
                        'female' => 649,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 730,
                        'new' => 84,
                        'graduate' => 66,
                        'inactive' => 18,
                        'male' => 381,
                        'female' => 517,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 690,
                        'new' => 79,
                        'graduate' => 56,
                        'inactive' => 15,
                        'male' => 284,
                        'female' => 556,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 628,
                        'new' => 64,
                        'graduate' => 48,
                        'inactive' => 13,
                        'male' => 219,
                        'female' => 534,
                    ],
                ],
            ],
            '2023/2024' => [
                'Ganjil' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1195,
                        'new' => 172,
                        'graduate' => 98,
                        'inactive' => 31,
                        'male' => 742,
                        'female' => 754,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 946,
                        'new' => 118,
                        'graduate' => 81,
                        'inactive' => 26,
                        'male' => 521,
                        'female' => 650,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1062,
                        'new' => 141,
                        'graduate' => 88,
                        'inactive' => 35,
                        'male' => 833,
                        'female' => 493,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 845,
                        'new' => 104,
                        'graduate' => 74,
                        'inactive' => 25,
                        'male' => 408,
                        'female' => 640,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 723,
                        'new' => 81,
                        'graduate' => 59,
                        'inactive' => 19,
                        'male' => 377,
                        'female' => 505,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 681,
                        'new' => 77,
                        'graduate' => 52,
                        'inactive' => 16,
                        'male' => 281,
                        'female' => 545,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 617,
                        'new' => 61,
                        'graduate' => 44,
                        'inactive' => 12,
                        'male' => 214,
                        'female' => 520,
                    ],
                ],
                'Genap' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1170,
                        'new' => 160,
                        'graduate' => 107,
                        'inactive' => 29,
                        'male' => 728,
                        'female' => 738,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 928,
                        'new' => 110,
                        'graduate' => 79,
                        'inactive' => 23,
                        'male' => 516,
                        'female' => 624,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1045,
                        'new' => 133,
                        'graduate' => 85,
                        'inactive' => 32,
                        'male' => 820,
                        'female' => 475,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 833,
                        'new' => 97,
                        'graduate' => 72,
                        'inactive' => 24,
                        'male' => 399,
                        'female' => 627,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 712,
                        'new' => 78,
                        'graduate' => 56,
                        'inactive' => 17,
                        'male' => 371,
                        'female' => 492,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 665,
                        'new' => 73,
                        'graduate' => 49,
                        'inactive' => 15,
                        'male' => 275,
                        'female' => 527,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 603,
                        'new' => 58,
                        'graduate' => 43,
                        'inactive' => 11,
                        'male' => 208,
                        'female' => 507,
                    ],
                ],
                'Pendek' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1153,
                        'new' => 148,
                        'graduate' => 101,
                        'inactive' => 27,
                        'male' => 720,
                        'female' => 709,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 915,
                        'new' => 106,
                        'graduate' => 76,
                        'inactive' => 22,
                        'male' => 507,
                        'female' => 612,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1029,
                        'new' => 126,
                        'graduate' => 83,
                        'inactive' => 29,
                        'male' => 810,
                        'female' => 458,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 820,
                        'new' => 92,
                        'graduate' => 69,
                        'inactive' => 22,
                        'male' => 391,
                        'female' => 612,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 701,
                        'new' => 75,
                        'graduate' => 53,
                        'inactive' => 16,
                        'male' => 365,
                        'female' => 480,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 652,
                        'new' => 69,
                        'graduate' => 46,
                        'inactive' => 14,
                        'male' => 269,
                        'female' => 512,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 592,
                        'new' => 52,
                        'graduate' => 38,
                        'inactive' => 10,
                        'male' => 203,
                        'female' => 489,
                    ],
                ],
            ],
            '2022/2023' => [
                'Ganjil' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1120,
                        'new' => 139,
                        'graduate' => 94,
                        'inactive' => 25,
                        'male' => 701,
                        'female' => 677,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 892,
                        'new' => 98,
                        'graduate' => 73,
                        'inactive' => 20,
                        'male' => 492,
                        'female' => 591,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 1004,
                        'new' => 121,
                        'graduate' => 79,
                        'inactive' => 27,
                        'male' => 787,
                        'female' => 444,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 792,
                        'new' => 88,
                        'graduate' => 64,
                        'inactive' => 20,
                        'male' => 376,
                        'female' => 588,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 690,
                        'new' => 69,
                        'graduate' => 51,
                        'inactive' => 15,
                        'male' => 359,
                        'female' => 466,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 635,
                        'new' => 62,
                        'graduate' => 41,
                        'inactive' => 12,
                        'male' => 259,
                        'female' => 491,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 571,
                        'new' => 46,
                        'graduate' => 34,
                        'inactive' => 9,
                        'male' => 194,
                        'female' => 466,
                    ],
                ],
                'Genap' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1094,
                        'new' => 128,
                        'graduate' => 88,
                        'inactive' => 23,
                        'male' => 689,
                        'female' => 644,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 876,
                        'new' => 92,
                        'graduate' => 69,
                        'inactive' => 18,
                        'male' => 483,
                        'female' => 564,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 989,
                        'new' => 115,
                        'graduate' => 74,
                        'inactive' => 25,
                        'male' => 774,
                        'female' => 404,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 774,
                        'new' => 82,
                        'graduate' => 59,
                        'inactive' => 18,
                        'male' => 365,
                        'female' => 568,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 675,
                        'new' => 63,
                        'graduate' => 47,
                        'inactive' => 13,
                        'male' => 351,
                        'female' => 447,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 620,
                        'new' => 58,
                        'graduate' => 38,
                        'inactive' => 11,
                        'male' => 251,
                        'female' => 476,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 556,
                        'new' => 41,
                        'graduate' => 29,
                        'inactive' => 8,
                        'male' => 186,
                        'female' => 448,
                    ],
                ],
                'Pendek' => [
                    [
                        'name' => 'FKIP',
                        'active' => 1081,
                        'new' => 121,
                        'graduate' => 84,
                        'inactive' => 22,
                        'male' => 681,
                        'female' => 627,
                    ],
                    [
                        'name' => 'FEB',
                        'active' => 862,
                        'new' => 88,
                        'graduate' => 66,
                        'inactive' => 17,
                        'male' => 476,
                        'female' => 557,
                    ],
                    [
                        'name' => 'FT',
                        'active' => 978,
                        'new' => 109,
                        'graduate' => 71,
                        'inactive' => 23,
                        'male' => 767,
                        'female' => 391,
                    ],
                    [
                        'name' => 'FISIP',
                        'active' => 761,
                        'new' => 77,
                        'graduate' => 55,
                        'inactive' => 17,
                        'male' => 359,
                        'female' => 541,
                    ],
                    [
                        'name' => 'FH',
                        'active' => 660,
                        'new' => 58,
                        'graduate' => 42,
                        'inactive' => 12,
                        'male' => 342,
                        'female' => 430,
                    ],
                    [
                        'name' => 'FP',
                        'active' => 606,
                        'new' => 52,
                        'graduate' => 34,
                        'inactive' => 10,
                        'male' => 244,
                        'female' => 462,
                    ],
                    [
                        'name' => 'FK',
                        'active' => 545,
                        'new' => 38,
                        'graduate' => 26,
                        'inactive' => 7,
                        'male' => 179,
                        'female' => 437,
                    ],
                ],
            ],
        ];
    }
}
